### ISSUE TITLE
`plasmapy.particles.Particle("C 1+").nuclide_mass` raises InvalidIsotopeError

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#1201]
```python
>>> plasmapy.particles.Particle("C 1+").nuclide_mass
Traceback (most recent call last):
  File "<ipython-input-5-419d156dc7c8>", line 1, in <module>
    plasmapy.particles.Particle("C 1+").nuclide_mass
  File "/home/dominik/Code/PlasmaPy/plasmapy/particles/particle_class.py", line 1107, in nuclide_mass
    raise InvalidIsotopeError(_category_errmsg(self, "isotope"))
InvalidIsotopeError: The particle C 1+ is not an isotope, so this attribute is not available.
```

Is this actually all that reasonable? The nuclide mass would just be the mass of the neutrons and protons, and I would expect `p.nuclide_mass` to be the same between all charge states of C. The `.mass` we can argue about, but `nuclide_mass` should most likely be invariant.

**Comment by namurphy** [comment]
The reason why I had `Particle("C 1+").nuclide_mass` raise an exception is that a nuclide is defined to have a specific number of protons and neutrons, and this statement does not specify a mass number.  With that said... I looked over the literature and it's a bit confusing about whether or not a "nuclide" specifically refers to a nucleus or if different ionic levels are allowed.  Maybe it would be better to have the attribute be named `nucleus_mass`.  

Another issue with standard atomic weight is that it assumes the terrestrial breakdown of isotopes for each element.  Since the job of an astronomer involves thinking about all parts of the universe _besides_ Earth, this is not the most useful definition to me.

One of the things I had been thinking of doing in #687 one of these decades was to have `nuclide_mass` only be an attribute for subclasses of `Isotope`.  I think this is something that will require more discussion and thinking...sigh!

**Comment by namurphy** [comment]
Most of the conversations I'm having about the `Particle` class these days remind me of a quote from the _X-files_:

> Regret is an inevitable consequence of life.

**Comment by StanczakDominik** [comment]
> The reason why I had `Particle("C 1+").nuclide_mass` raise an exception is that a nuclide is defined to have a specific number of protons and neutrons, and this statement does not specify a mass number. With that said... I looked over the literature and it's a bit confusing about whether or not a "nuclide" specifically refers to a nucleus or if different ionic levels are allowed. Maybe it would be better to have the attribute be named `nucleus_mass`.

👍🏻 

> Another issue with standard atomic weight is that it assumes the terrestrial breakdown of isotopes for each element. Since the job of an astronomer involves thinking about all parts of the universe _besides_ Earth, this is not the most useful definition to me.

True, but it would be quite helpful for most Earth-based plasmas, no?
