### ISSUE TITLE
Bug in `Particle.__eq__` for protons

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1363]
I'm finding differences between protons created by `Particle("p+")` and `Particle("H", Z=1, mass_numb=1)`, as follows.

```Python
>>> from plasmapy.particles import Particle
>>> proton = Particle("p+")
>>> should_be_proton = Particle("H", Z=1, mass_numb=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/namurphy/.miniconda/lib/python3.9/site-packages/plasmapy-0.0.0-py3.9.egg/plasmapy/particles/particle_class.py", line 665, in __eq__
    raise ParticleError(
plasmapy.particles.exceptions.ParticleError: p+ and p+ should be the same Particle, but have differing attributes.

The attributes of p+ are:

defaultdict(<class 'NoneType'>, {'symbol': 'p+', 'element': 'H', 'atomic number': 1, 'mass number': 1, 'element name': 'hydrogen', 'isotope': 'H-1', 'ion': 'p+', 'mass': <<class 'astropy.constants.codata2018.CODATA2018'> name='Proton mass' value=1.67262192369e-27 uncertainty=5.1e-37 unit='kg' reference='CODATA 2018'>, 'charge number': 1, 'periodic table': _PeriodicTable(group=1, period=1, block='s', category='nonmetal'), 'name': 'proton', 'spin': 0.5, 'class': 'baryon', 'lepton number': 0, 'baryon number': 1, 'half-life': <Quantity inf s>, 'antimatter': False, 'charge': <<class 'astropy.constants.codata2018.EMCODATA2018'> name='Electron charge' value=1.602176634e-19 uncertainty=0.0 unit='C' reference='CODATA 2018'>, 'isotope mass': None, 'isotopic abundance': None})

The attributes of p+ are:

defaultdict(<class 'NoneType'>, {'symbol': 'p+', 'element': 'H', 'isotope': 'H-1', 'ion': 'p+', 'mass number': 1, 'charge number': 1, 'atomic number': 1, 'element name': 'hydrogen', 'lepton number': 0, 'baryon number': 1, 'isotope mass': <Quantity 1.00782503 u>, 'isotopic abundance': 0.999885, 'half-life': <Quantity inf s>, 'mass': <<class 'astropy.constants.codata2018.CODATA2018'> name='Proton mass' value=1.67262192369e-27 uncertainty=5.1e-37 unit='kg' reference='CODATA 2018'>, 'periodic table': _PeriodicTable(group=1, period=1, block='s', category='nonmetal'), 'charge': <<class 'astropy.constants.codata2018.EMCODATA2018'> name='Electron charge' value=1.602176634e-19 uncertainty=0.0 unit='C' reference='CODATA 2018'>, 'name': None, 'spin': None, 'class': None, 'antimatter': None})
>>> proton._attributes == should_be_proton._attributes
False
>>> for key, val in proton._attributes.items():
...     new_val = should_be_proton._attributes[key]
...     if val != new_val:
...         print(f"{key}: {val}, {new_val}")
name: proton, None
spin: 0.5, None
class: baryon, None
antimatter: False, None
isotope mass: None, 1.00782503223 u
isotopic abundance: None, 0.999885
```
So far I've only found this discrepancy for protons, but it's good practice to test exhaustively for bugs, so the fix should include similar tests for protons, deuterons, tritons, and alphas.  Yay for special cases...

**Comment by namurphy** [comment]
A quick test could be something like:
```Python
@pytest.mark.parametrize("particle", ["p+", "D+", "T+", "alpha"])
def test_particle_equality_special_nuclides(particle):
    particle_from_string = Particle(particle)
    particle_from_numbers = Particle(
        particle_from_string.element_name,
        Z = particle_from_string.charge_number,
        mass_numb = particle_from_string.mass_number,
    )
    assert particle_from_string == particle_from_numbers
    assert particle_from_string._attributes == particle_from_numbers._attributes
```
