### ISSUE TITLE
Dependency conflict between NumPy and Numba when installing `v0.8.1` with conda

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1637]
I am getting the following error, which means something is wrong with [PlasmaPy's conda-forge feedstock](https://github.com/conda-forge/plasmapy-feedstock).  

- I tried creating an environment whilst installing `v0.8.1` via conda-forge.  It went through with no errors.
- I activated the environment and opened Python.
- I tried `import plasmapy` and got an error that `Numba needs NumPy 1.21 or less`

```shell
$ conda create -n sdfasdf python=3.10 plasmapy=0.8.1 -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/namurphy/miniconda3/envs/sdfasdf

  added / updated specs:
    - plasmapy=0.8.1
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fonttools-4.34.4           |  py310h5764c6d_0         1.7 MB  conda-forge
    ipykernel-6.15.1           |     pyh210e3f2_0          96 KB  conda-forge
    jsonschema-4.6.2           |     pyhd8ed1ab_0          63 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  anyio              conda-forge/linux-64::anyio-3.6.1-py310hff52083_0
  argon2-cffi        conda-forge/noarch::argon2-cffi-21.3.0-pyhd8ed1ab_0
  argon2-cffi-bindi~ conda-forge/linux-64::argon2-cffi-bindings-21.2.0-py310h5764c6d_2
  asteval            conda-forge/noarch::asteval-0.9.27-pyhd8ed1ab_0
  astropy            conda-forge/linux-64::astropy-5.1-py310hde88566_0
  asttokens          conda-forge/noarch::asttokens-2.0.5-pyhd8ed1ab_0
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  backcall           conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0
  backports          conda-forge/noarch::backports-1.0-py_2
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.4-pyhd8ed1ab_0
  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.11.1-pyha770c72_0
  bleach             conda-forge/noarch::bleach-5.0.1-pyhd8ed1ab_0
  brotli             conda-forge/linux-64::brotli-1.0.9-h166bdaf_7
  brotli-bin         conda-forge/linux-64::brotli-bin-1.0.9-h166bdaf_7
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  c-ares             conda-forge/linux-64::c-ares-1.18.1-h7f98852_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2022.6.15-ha878542_0
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
  certifi            conda-forge/linux-64::certifi-2022.6.15-py310hff52083_0
  cffi               conda-forge/linux-64::cffi-1.15.1-py310h255011f_0
  colorama           conda-forge/noarch::colorama-0.4.5-pyhd8ed1ab_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  debugpy            conda-forge/linux-64::debugpy-1.6.0-py310hd8f1fbe_0
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
  defusedxml         conda-forge/noarch::defusedxml-0.7.1-pyhd8ed1ab_0
  entrypoints        conda-forge/noarch::entrypoints-0.4-pyhd8ed1ab_0
  executing          conda-forge/noarch::executing-0.8.3-pyhd8ed1ab_0
  flit-core          conda-forge/noarch::flit-core-3.7.1-pyhd8ed1ab_0
  fonttools          conda-forge/linux-64::fonttools-4.34.4-py310h5764c6d_0
  freetype           conda-forge/linux-64::freetype-2.10.4-h0708190_1
  future             conda-forge/linux-64::future-0.18.2-py310hff52083_5
  giflib             conda-forge/linux-64::giflib-5.2.1-h36c2ea0_2
  h5py               conda-forge/linux-64::h5py-3.7.0-nompi_py310h06dffec_100
  hdf5               conda-forge/linux-64::hdf5-1.12.1-nompi_h4df4325_104
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  importlib-metadata conda-forge/linux-64::importlib-metadata-4.11.4-py310hff52083_0
  importlib_metadata conda-forge/noarch::importlib_metadata-4.11.4-hd8ed1ab_0
  importlib_resourc~ conda-forge/noarch::importlib_resources-5.8.0-pyhd8ed1ab_0
  ipykernel          conda-forge/noarch::ipykernel-6.15.1-pyh210e3f2_0
  ipython            conda-forge/linux-64::ipython-8.4.0-py310hff52083_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.7.1-pyhd8ed1ab_0
  jedi               conda-forge/linux-64::jedi-0.18.1-py310hff52083_1
  jinja2             conda-forge/noarch::jinja2-3.1.2-pyhd8ed1ab_1
  jpeg               conda-forge/linux-64::jpeg-9e-h166bdaf_2
  jsonschema         conda-forge/noarch::jsonschema-4.6.2-pyhd8ed1ab_0
  jupyter_client     conda-forge/noarch::jupyter_client-7.3.4-pyhd8ed1ab_0
  jupyter_core       conda-forge/linux-64::jupyter_core-4.10.0-py310hff52083_0
  jupyter_server     conda-forge/noarch::jupyter_server-1.18.1-pyhd8ed1ab_0
  jupyterlab_pygmen~ conda-forge/noarch::jupyterlab_pygments-0.2.2-pyhd8ed1ab_0
  jupyterlab_widgets conda-forge/noarch::jupyterlab_widgets-1.1.1-pyhd8ed1ab_0
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0
  kiwisolver         conda-forge/linux-64::kiwisolver-1.4.3-py310hbf28c38_0
  krb5               conda-forge/linux-64::krb5-1.19.3-h08a2579_0
  lcms2              conda-forge/linux-64::lcms2-2.12-hddcbb42_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  lerc               conda-forge/linux-64::lerc-3.0-h9c3ff4c_0
  libblas            conda-forge/linux-64::libblas-3.9.0-15_linux64_openblas
  libbrotlicommon    conda-forge/linux-64::libbrotlicommon-1.0.9-h166bdaf_7
  libbrotlidec       conda-forge/linux-64::libbrotlidec-1.0.9-h166bdaf_7
  libbrotlienc       conda-forge/linux-64::libbrotlienc-1.0.9-h166bdaf_7
  libcblas           conda-forge/linux-64::libcblas-3.9.0-15_linux64_openblas
  libcurl            conda-forge/linux-64::libcurl-7.83.1-h2283fc2_0
  libdeflate         conda-forge/linux-64::libdeflate-1.12-h166bdaf_0
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-h516909a_1
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-12.1.0-h8d9b700_16
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-12.1.0-h69a702a_16
  libgfortran5       conda-forge/linux-64::libgfortran5-12.1.0-hdcd56e2_16
  libgomp            conda-forge/linux-64::libgomp-12.1.0-h8d9b700_16
  liblapack          conda-forge/linux-64::liblapack-3.9.0-15_linux64_openblas
  libllvm11          conda-forge/linux-64::libllvm11-11.1.0-hf817b99_3
  libnghttp2         conda-forge/linux-64::libnghttp2-1.47.0-he49606f_0
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.20-pthreads_h78a6416_0
  libpng             conda-forge/linux-64::libpng-1.6.37-h753d276_3
  libsodium          conda-forge/linux-64::libsodium-1.0.18-h36c2ea0_1
  libssh2            conda-forge/linux-64::libssh2-1.10.0-ha35d2d1_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-12.1.0-ha89aaad_16
  libtiff            conda-forge/linux-64::libtiff-4.4.0-hc85c160_1
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h7f98852_1000
  libwebp            conda-forge/linux-64::libwebp-1.2.2-h3452ae3_0
  libwebp-base       conda-forge/linux-64::libwebp-base-1.2.2-h7f98852_1
  libxcb             conda-forge/linux-64::libxcb-1.13-h7f98852_1004
  libzlib            conda-forge/linux-64::libzlib-1.2.12-h166bdaf_1
  llvmlite           conda-forge/linux-64::llvmlite-0.38.1-py310h58363a5_0
  lmfit              conda-forge/noarch::lmfit-1.0.3-pyhd8ed1ab_0
  lz4-c              conda-forge/linux-64::lz4-c-1.9.3-h9c3ff4c_1
  markupsafe         conda-forge/linux-64::markupsafe-2.1.1-py310h5764c6d_1
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.5.2-py310h5701ce4_0
  matplotlib-inline  conda-forge/noarch::matplotlib-inline-0.1.3-pyhd8ed1ab_0
  mistune            conda-forge/linux-64::mistune-0.8.4-py310h6acc77f_1005
  mpmath             conda-forge/noarch::mpmath-1.2.1-pyhd8ed1ab_0
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0
  nbclient           conda-forge/noarch::nbclient-0.5.13-pyhd8ed1ab_0
  nbconvert          conda-forge/noarch::nbconvert-6.5.0-pyhd8ed1ab_0
  nbconvert-core     conda-forge/noarch::nbconvert-core-6.5.0-pyhd8ed1ab_0
  nbconvert-pandoc   conda-forge/noarch::nbconvert-pandoc-6.5.0-pyhd8ed1ab_0
  nbformat           conda-forge/noarch::nbformat-5.4.0-pyhd8ed1ab_0
  ncurses            conda-forge/linux-64::ncurses-6.3-h27087fc_1
  nest-asyncio       conda-forge/noarch::nest-asyncio-1.5.5-pyhd8ed1ab_0
  notebook           conda-forge/noarch::notebook-6.4.12-pyha770c72_0
  numba              pkgs/main/linux-64::numba-0.55.0-py310h00e6091_0
  numpy              conda-forge/linux-64::numpy-1.23.0-py310h53a5b5f_0
  openjpeg           conda-forge/linux-64::openjpeg-2.4.0-hb52868f_1
  openssl            conda-forge/linux-64::openssl-3.0.5-h166bdaf_0
  packaging          conda-forge/noarch::packaging-21.3-pyhd8ed1ab_0
  pandas             conda-forge/linux-64::pandas-1.4.3-py310h769672d_0
  pandoc             conda-forge/linux-64::pandoc-2.18-ha770c72_0
  pandocfilters      conda-forge/noarch::pandocfilters-1.5.0-pyhd8ed1ab_0
  parso              conda-forge/noarch::parso-0.8.3-pyhd8ed1ab_0
  pexpect            conda-forge/noarch::pexpect-4.8.0-pyh9f0ad1d_2
  pickleshare        conda-forge/noarch::pickleshare-0.7.5-py_1003
  pillow             conda-forge/linux-64::pillow-9.2.0-py310he619898_0
  pip                conda-forge/noarch::pip-22.1.2-pyhd8ed1ab_0
  plasmapy           conda-forge/noarch::plasmapy-0.8.1-pyhd8ed1ab_0
  prometheus_client  conda-forge/noarch::prometheus_client-0.14.1-pyhd8ed1ab_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.30-pyha770c72_0
  psutil             conda-forge/linux-64::psutil-5.9.1-py310h5764c6d_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h36c2ea0_1001
  ptyprocess         conda-forge/noarch::ptyprocess-0.7.0-pyhd3deb0d_0
  pure_eval          conda-forge/noarch::pure_eval-0.2.2-pyhd8ed1ab_0
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pyerfa             conda-forge/linux-64::pyerfa-2.0.0.1-py310hde88566_2
  pygments           conda-forge/noarch::pygments-2.12.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.9-pyhd8ed1ab_0
  pyrsistent         conda-forge/linux-64::pyrsistent-0.18.1-py310h5764c6d_1
  python             conda-forge/linux-64::python-3.10.5-ha86cf86_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python-fastjsonsc~ conda-forge/noarch::python-fastjsonschema-2.15.3-pyhd8ed1ab_0
  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310
  pytz               conda-forge/noarch::pytz-2022.1-pyhd8ed1ab_0
  pyyaml             conda-forge/linux-64::pyyaml-6.0-py310h5764c6d_4
  pyzmq              conda-forge/linux-64::pyzmq-23.2.0-py310h330234f_0
  readline           conda-forge/linux-64::readline-8.1.2-h0f457ee_0
  scipy              conda-forge/linux-64::scipy-1.8.1-py310h7612f91_0
  send2trash         conda-forge/noarch::send2trash-1.8.0-pyhd8ed1ab_0
  setuptools         conda-forge/linux-64::setuptools-63.1.0-py310hff52083_0
  setuptools-scm     conda-forge/noarch::setuptools-scm-7.0.4-pyhd8ed1ab_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sniffio            conda-forge/linux-64::sniffio-1.2.0-py310hff52083_3
  soupsieve          conda-forge/noarch::soupsieve-2.3.1-pyhd8ed1ab_0
  sqlite             conda-forge/linux-64::sqlite-3.39.0-h4ff8645_0
  stack_data         conda-forge/noarch::stack_data-0.3.0-pyhd8ed1ab_0
  tbb                conda-forge/linux-64::tbb-2021.5.0-h924138e_1
  terminado          conda-forge/linux-64::terminado-0.15.0-py310hff52083_0
  tinycss2           conda-forge/noarch::tinycss2-1.1.1-pyhd8ed1ab_0
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0
  tomli              conda-forge/noarch::tomli-2.0.1-pyhd8ed1ab_0
  tornado            conda-forge/linux-64::tornado-6.2-py310h5764c6d_0
  tqdm               conda-forge/noarch::tqdm-4.64.0-pyhd8ed1ab_0
  traitlets          conda-forge/noarch::traitlets-5.3.0-pyhd8ed1ab_0
  typing-extensions  conda-forge/noarch::typing-extensions-4.3.0-hd8ed1ab_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.3.0-pyha770c72_0
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  uncertainties      conda-forge/noarch::uncertainties-3.1.7-pyhd8ed1ab_0
  unicodedata2       conda-forge/linux-64::unicodedata2-14.0.0-py310h5764c6d_1
  voila              conda-forge/noarch::voila-0.3.1-pyhd8ed1ab_0
  wcwidth            conda-forge/noarch::wcwidth-0.2.5-pyh9f0ad1d_2
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  websocket-client   conda-forge/noarch::websocket-client-1.3.3-pyhd8ed1ab_0
  websockets         conda-forge/linux-64::websockets-10.3-py310h5764c6d_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  widgetsnbextension conda-forge/noarch::widgetsnbextension-3.6.1-pyha770c72_0
  xarray             conda-forge/noarch::xarray-2022.3.0-pyhd8ed1ab_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h7f98852_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h7f98852_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  yaml               conda-forge/linux-64::yaml-0.2.5-h7f98852_2
  zeromq             conda-forge/linux-64::zeromq-4.3.4-h9c3ff4c_1
  zipp               conda-forge/noarch::zipp-3.8.0-pyhd8ed1ab_0
  zlib               conda-forge/linux-64::zlib-1.2.12-h166bdaf_1
  zstd               conda-forge/linux-64::zstd-1.5.2-h8a70e8d_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
jsonschema-4.6.2     | 63 KB     | ################################################# | 100% 
ipykernel-6.15.1     | 96 KB     | ################################################# | 100% 
fonttools-4.34.4     | 1.7 MB    | ################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate sdfasdf
#
# To deactivate an active environment, use
#
#     $ conda deactivate


$ conda activate sdfasdf
(sdfasdf) 
$ python
Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:06:46) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import plasmapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/namurphy/miniconda3/envs/sdfasdf/lib/python3.10/site-packages/plasmapy/__init__.py", line 33, in <module>
    from plasmapy import (
  File "/home/namurphy/miniconda3/envs/sdfasdf/lib/python3.10/site-packages/plasmapy/analysis/__init__.py", line 4, in <module>
    from plasmapy.analysis import fit_functions, nullpoint, swept_langmuir
  File "/home/namurphy/miniconda3/envs/sdfasdf/lib/python3.10/site-packages/plasmapy/analysis/fit_functions.py", line 23, in <module>
    from plasmapy.utils.decorators import modify_docstring
  File "/home/namurphy/miniconda3/envs/sdfasdf/lib/python3.10/site-packages/plasmapy/utils/__init__.py", line 20, in <module>
    from plasmapy.utils import (
  File "/home/namurphy/miniconda3/envs/sdfasdf/lib/python3.10/site-packages/plasmapy/utils/decorators/__init__.py", line 31, in <module>
    from plasmapy.utils.decorators.lite_func import bind_lite_func
  File "/home/namurphy/miniconda3/envs/sdfasdf/lib/python3.10/site-packages/plasmapy/utils/decorators/lite_func.py", line 10, in <module>
    from numba.extending import is_jitted
  File "/home/namurphy/miniconda3/envs/sdfasdf/lib/python3.10/site-packages/numba/__init__.py", line 200, in <module>
    _ensure_critical_deps()
  File "/home/namurphy/miniconda3/envs/sdfasdf/lib/python3.10/site-packages/numba/__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.21 or less")
ImportError: Numba needs NumPy 1.21 or less
```

**Comment by rocco8773** [comment]
This is the same thing that is affecting the binder session for the `hack-week` repo.

**Comment by namurphy** [comment]
Yep...sigh.  

Given that we've run into issues with the maximum version of Numba a couple of times now, I've been starting to lean towards switching to Cython and dropping Numba.  But that's not something to decide today...

**Comment by namurphy** [comment]
I think I got it to work with https://github.com/conda-forge/plasmapy-feedstock/pull/20 but this is something we'll need to come back to.
