### ISSUE TITLE
Fix the GitHub Action that comments on pull requests

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1965]
In #1956, a change was made to switch the GitHub Action that comments on pull requests, based off of what was implemented in Astropy.  However, we're now getting an error from that which we need to fix: 
```
SyntaxError: Unexpected identifier
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13356:16)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13452:26)
    at Module.858 (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13429:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:52:10)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
Error: Unhandled error: SyntaxError: Unexpected identifier
```
It would have been helpful if the error message had said what the unexpected identifier was, but alas!

**Comment by namurphy** [comment]
FYI, this action was [temporarily removed](https://github.com/PlasmaPy/PlasmaPy/commit/fc12bbd286ae9db82ab313d8c380808b814a462c) pending a fix.

**Comment by namurphy** [comment]
#2044 added back the GitHub Action that adds the checklist as a comment.  The problem was that I needed to add a `\` before the backticks for Markdown formatting because backticks are also being used to demarcate the text block.  The error message for this was not particularly helpful.

This issue is still waiting on the first interaction GitHub Action being added back in.
