### ISSUE TITLE
Getting internal errors when running Nox locally

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2855]
When I tried running `nox` locally on my workstation, I ended up getting the errors below.  These errors didn't happen when I ran `pytest` directly, and they didn't happen either when I ran `nox` but only have specifying in `noxfile.py` that the uv backend shouldn't be used.  It seems very likely that this is not a problem with PlasmaPy itself, and has something to do with the uv backend for Nox.  But, I have no idea what!

I was running this on RHEL, using a version of uv that I installed outside of my Python distribution.

```
<ExceptionInfo ImportError("cannot import name 'IntervalSaveRoutine' from 'plasmapy.simulation.particle_tracker' (/run/media/namurphy...ects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/plasmapy/simulation/particle_tracker/__init__.py)") tblen=22>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/xdist/workermanage.py", line 435, in process_from_remote
INTERNALERROR>     warning_message = unserialize_warning_message(
INTERNALERROR>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/xdist/workermanage.py", line 462, in unserialize_warning_message
INTERNALERROR>     mod = importlib.import_module(data["message_module"])
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Applications/miniconda3/envs/pldev/lib/python3.12/importlib/__init__.py", line 90, in import_module
INTERNALERROR>     return _bootstrap._gcd_import(name[level:], package, level)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/plasmapy/__init__.py", line 36, in <module>
INTERNALERROR>     from plasmapy import (
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/plasmapy/diagnostics/__init__.py", line 8, in <module>
INTERNALERROR>     from plasmapy.diagnostics import charged_particle_radiography, langmuir, thomson
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/plasmapy/diagnostics/charged_particle_radiography/__init__.py", line 8, in <module>
INTERNALERROR>     from plasmapy.diagnostics.charged_particle_radiography import (
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/plasmapy/diagnostics/charged_particle_radiography/synthetic_radiography.py", line 24, in <module>
INTERNALERROR>     from plasmapy.simulation.particle_tracker.particle_tracker import ParticleTracker
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/plasmapy/simulation/__init__.py", line 26, in <module>
INTERNALERROR>     from plasmapy.simulation.particle_tracker import (
INTERNALERROR> ImportError: cannot import name 'IntervalSaveRoutine' from 'plasmapy.simulation.particle_tracker' (/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/plasmapy/simulation/particle_tracker/__init__.py)
[gw0] node down: <ExceptionInfo ImportError("cannot import name 'IntervalSaveRoutine' from 'plasmapy.simulation.particle_tracker' (/run/media/namurphy...ects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/plasmapy/simulation/particle_tracker/__init__.py)") tblen=22>
F
replacing crashed worker gw0
collecting: 8/9 workersINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/_pytest/main.py", line 283, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/_pytest/main.py", line 337, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/_pytest/logging.py", line 805, in pytest_runtestloop
INTERNALERROR>     return (yield)  # Run all the tests.
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/_pytest/terminal.py", line 673, in pytest_runtestloop
INTERNALERROR>     result = yield
INTERNALERROR>              ^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/xdist/dsession.py", line 138, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/xdist/dsession.py", line 163, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/xdist/dsession.py", line 341, in worker_runtest_protocol_complete
INTERNALERROR>     self.sched.mark_test_complete(node, item_index, duration)
INTERNALERROR>   File "/run/media/namurphy/d423d80e-c227-4a33-b50f-545b44160ce3/namurphy/Projects/PlasmaPy/.nox/tests-3-12-skipslow/lib/python3.12/site-packages/xdist/scheduler/loadscope.py", line 250, in mark_test_complete
INTERNALERROR>     self.assigned_work[node][scope][nodeid] = True
INTERNALERROR>     ~~~~~~~~~~~~~~~~~~^^^^^^
INTERNALERROR> KeyError: <WorkerController gw0>
```

**Comment by namurphy** [comment]
I _think_ this issue was caused by mixing up separate installations of uv & Python, so I'm going to tentatively close this.  If anyone else experiences it, we can re-open it.
