### ISSUE TITLE
While importing pytplot getting following error

### ISSUE THREAD

**Issue by ramsinghdayal** [PlasmaPy/PlasmaPy#322]
```
import pytplot
Traceback (most recent call last):

  File "<ipython-input-40-aca30a9a5872>", line 1, in <module>
    import pytplot

  File "/Users/ram/MAVENSDC/PyTplot-master/pytplot/__init__.py", line 190, in <module>
    from .tplot import tplot

  File "/Users/ram/MAVENSDC/PyTplot-master/pytplot/tplot.py", line 8, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView as WebView

ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created
```

Even tried this, before importing pytplot but gives same error.
```
from PyQt5 import QtWebEngineWidgets as webview
Traceback (most recent call last):

  File "<ipython-input-37-988044e720bd>", line 1, in <module>
    from PyQt5 import QtWebEngineWidgets as webview

ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created
```

**Comment by StanczakDominik** [comment]
What's pytplot? Are you sure this is a PlasmaPy issue?

**Comment by ramsinghdayal** [comment]
https://github.com/MAVENSDC/PyTplot
This is PyTplot, which I am trying to install. 
Thank you.

**Comment by StanczakDominik** [comment]
It would probably make sense to make an issue over at that repository then. I'm going to close this, as pytplot is neither a part nor a requirement of PlasmaPy.
