### ISSUE TITLE
`plot_langmuir_analysis.py` example fails with astropy v3.0.2

### ISSUE THREAD

**Issue by ritiek** [PlasmaPy/PlasmaPy#467]
Looks like astropy/astropy#7037 (released with astropy v3.0.2) broke our [plot_langmuir_analysis.py](https://github.com/PlasmaPy/PlasmaPy/blob/d405db0dba696ff6ca3f9bae7337ad75c57570a0/plasmapy/examples/plot_langmuir_analysis.py) example. Works fine with astropy v3.0.1 though.

```
$ cd plasmapy/examples
$ python plot_langmuir_analysis.py
Traceback (most recent call last):
  File "plot_langmuir_analysis.py", line 44, in <module>
    plot_EEDF=True))
  File "/home/ritiek/Downloads/PlasmaPy/plasmapy/utils/checks.py", line 119, in wrapper
    return f(**given_params_values)
  File "/home/ritiek/Downloads/PlasmaPy/plasmapy/diagnostics/langmuir.py", line 339, in swept_probe_analysis
    ax1.axvline(x=V_P.value, color='gray', linestyle='--')
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 792, in axvline
    self.add_line(l)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1793, in add_line
    self._update_line_limits(line)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1815, in _update_line_limits
    path = line.get_path()
  File "/usr/local/lib/python3.6/site-packages/matplotlib/lines.py", line 989, in get_path
    self.recache()
  File "/usr/local/lib/python3.6/site-packages/matplotlib/lines.py", line 672, in recache
    xconv = self.convert_xunits(self._xorig)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/artist.py", line 199, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axis.py", line 1472, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/usr/local/lib/python3.6/site-packages/astropy/visualization/units.py", line 84, in convert
    return [v.to_value(unit) for v in val]
  File "/usr/local/lib/python3.6/site-packages/astropy/visualization/units.py", line 84, in <listcomp>
    return [v.to_value(unit) for v in val]
AttributeError: 'float' object has no attribute 'to_value'
```

**Comment by StanczakDominik** [comment]
I think using Astropy's quantity plotting support would help here. Enable that, ax1.axvline(x=V_P.value, color='gray', linestyle='--')`, remove the `.value` part to keep it as a Quantity... yeah, that's gonna do it.

Takers? :D

**Comment by ritiek** [comment]
I tried to reproduce this again with astropy v3.0.3 but it looks like https://github.com/astropy/astropy/pull/7510 fixed this.
