### ISSUE TITLE
dimensionless.beta doesn't allow nans

### ISSUE THREAD

**Issue by dstansby** [PlasmaPy/PlasmaPy#523]
```python
from plasmapy.physics import dimensionless
import astropy.units as u
import numpy as np
dimensionless.beta(np.nan * u.K, 1 * u.cm**-3, 1 * u.T)
```
results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dstansby/github/plasmapy/plasmapy/utils/checks.py", line 157, in wrapper
    none_shall_pass=none_shall_pass)
  File "/Users/dstansby/github/plasmapy/plasmapy/utils/checks.py", line 319, in _check_quantity
    raise ValueError(f"{valueerror_message} NaNs.")
ValueError: The argument T to function beta cannot contain NaNs.
```

It would be nice if nans were propagated through functions like this instead of throwing an error.

**Comment by StanczakDominik** [comment]
Closed by #525
